# -*- coding: utf-8 -*-
"""ST_project_full_wikitext2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sONA-MhMHN6Vyj1_nciuJ81l5seH7m3d

# Soft-target next-token prediction on WikiText-2

This notebook compares standard hard-target language-model training with two soft alternatives: ordinary label smoothing and a similarity-based soft target. The main question is whether a representation-aware training target improves data efficiency, and whether any gain survives once runtime cost is taken into account.
"""

# ============================================================
# 0. Install
# ============================================================
!pip -q install transformers datasets accelerate tqdm

# ============================================================
# 1. Imports and config
# ============================================================
import math
import random
import numpy as np
from dataclasses import dataclass

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

from datasets import load_dataset
from transformers import AutoTokenizer, GPT2LMHeadModel, GPT2Config
from tqdm.auto import tqdm

seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

@dataclass
class CFG:
    dataset_name: str = "wikitext"
    dataset_config: str = "wikitext-2-raw-v1"

    tokenizer_name: str = "openai-community/gpt2"
    external_embedding_model: str = "openai-community/gpt2"

    block_size: int = 128
    batch_size: int = 4
    eval_batch_size: int = 4

    n_layer: int = 4
    n_head: int = 4
    n_embd: int = 256

    lr: float = 3e-4
    weight_decay: float = 0.01
    epochs: int = 1
    max_train_steps: int = 1000
    eval_every: int = 200

    tau: float = 0.07
    label_smoothing_epsilon: float = 0.05
    soft_loss_chunk_size: int = 128

    # Set to hard for baseline, soft for the project objective.
    train_objective: str = "soft"

cfg = CFG()

# ============================================================
# 2. Load WikiText-2 and tokenizer
# ============================================================
raw = load_dataset(cfg.dataset_name, cfg.dataset_config)
print(raw)

tokenizer = AutoTokenizer.from_pretrained(cfg.tokenizer_name)
tokenizer.pad_token = tokenizer.eos_token

def tokenize_fn(batch):
    return tokenizer(batch["text"])

tokenized = raw.map(
    tokenize_fn,
    batched=True,
    remove_columns=["text"],
    desc="Tokenizing"
)

def group_texts(examples):
    concatenated = []
    for ids in examples["input_ids"]:
        if len(ids) > 0:
            concatenated.extend(ids + [tokenizer.eos_token_id])

    total_length = (len(concatenated) // cfg.block_size) * cfg.block_size
    concatenated = concatenated[:total_length]

    input_ids = [
        concatenated[i : i + cfg.block_size]
        for i in range(0, total_length, cfg.block_size)
    ]

    return {
        "input_ids": input_ids,
        "attention_mask": [[1] * cfg.block_size for _ in input_ids],
    }

lm_datasets = tokenized.map(
    group_texts,
    batched=True,
    desc=f"Grouping into blocks of {cfg.block_size}"
)

lm_datasets.set_format(type="torch", columns=["input_ids", "attention_mask"])

train_loader = DataLoader(
    lm_datasets["train"],
    batch_size=cfg.batch_size,
    shuffle=True,
)

valid_loader = DataLoader(
    lm_datasets["validation"],
    batch_size=cfg.eval_batch_size,
    shuffle=False,
)

test_loader = DataLoader(
    lm_datasets["test"],
    batch_size=cfg.eval_batch_size,
    shuffle=False,
)

print("train batches:", len(train_loader))
print("valid batches:", len(valid_loader))
print("test batches:", len(test_loader))

# ============================================================
# 3. Build a small decoder-only LM from scratch
# ============================================================
model_config = GPT2Config(
    vocab_size=len(tokenizer),
    n_positions=cfg.block_size,
    n_ctx=cfg.block_size,
    n_embd=cfg.n_embd,
    n_layer=cfg.n_layer,
    n_head=cfg.n_head,
    bos_token_id=tokenizer.bos_token_id,
    eos_token_id=tokenizer.eos_token_id,
)

model = GPT2LMHeadModel(model_config).to(device)
print("number of parameters:", sum(p.numel() for p in model.parameters()) / 1e6, "M")

# ============================================================
# 4. Load fixed external GPT-2 token embeddings
# ============================================================
# These embeddings are NOT trained. They define q_soft(v | w_t).
with torch.no_grad():
    external_model = GPT2LMHeadModel.from_pretrained(cfg.external_embedding_model)
    ext_emb = external_model.transformer.wte.weight.detach().clone()

del external_model

ext_emb = ext_emb.to(device)
ext_emb = F.normalize(ext_emb, p=2, dim=-1)
# consine similarity = target_emb @ ext_emb.T

print("external embedding matrix:", ext_emb.shape)
print("vocab size:", len(tokenizer))

# ============================================================
# 5. Loss functions
# ============================================================
def hard_next_token_loss(logits, input_ids):
    """
    Standard next-token prediction:
    target is one-hot, implemented as class indices.
    """
    shift_logits = logits[:, :-1, :].contiguous()
    shift_labels = input_ids[:, 1:].contiguous()

    #next-token cross entropy/one-hot target
    loss = F.cross_entropy(
        shift_logits.view(-1, shift_logits.size(-1)),
        shift_labels.view(-1)
    )
    return loss

#soft-target next token loss
def label_smoothing_next_token_loss(logits, input_ids, epsilon=0.05):
    """
    Non-representational soft-target baseline.
    The observed token keeps most probability mass; the remaining mass is
    spread uniformly across the vocabulary by PyTorch's label_smoothing option.
    """
    shift_logits = logits[:, :-1, :].contiguous()
    shift_labels = input_ids[:, 1:].contiguous()

    loss = F.cross_entropy(
        shift_logits.view(-1, shift_logits.size(-1)),
        shift_labels.view(-1),
        label_smoothing=epsilon,
    )
    return loss


def soft_target_next_token_loss(
    logits,
    input_ids,
    ext_emb,
    tau=0.07,
    chunk_size=128,
):
    """
    Soft-target next-token prediction:

        q_soft(v | w_t) proportional to exp(cos(e_wt, e_v) / tau)

        loss = - sum_v q_soft(v | w_t) log p_model(v | context)

    ext_emb must be L2-normalized, so dot product is cosine similarity.
    """
    shift_logits = logits[:, :-1, :].contiguous()
    shift_labels = input_ids[:, 1:].contiguous()

    vocab_size = shift_logits.size(-1)

    logits_flat = shift_logits.view(-1, vocab_size)
    labels_flat = shift_labels.view(-1)

    total_loss = torch.zeros([], device=logits.device)
    total_count = 0

    for start in range(0, logits_flat.size(0), chunk_size):
        end = min(start + chunk_size, logits_flat.size(0))

        logits_chunk = logits_flat[start:end]
        labels_chunk = labels_flat[start:end]

        log_probs = F.log_softmax(logits_chunk, dim=-1)

        with torch.no_grad():
            target_emb = ext_emb[labels_chunk]
            sims = target_emb @ ext_emb.T
            q_soft = F.softmax(sims / tau, dim=-1)
            #next token embedding, calculate cosine similarity with vocab tokens, softmax+temperature.

        #soft loss
        loss_chunk = -(q_soft * log_probs).sum(dim=-1)
        total_loss = total_loss + loss_chunk.sum()
        total_count += loss_chunk.numel()

    return total_loss / total_count

# ============================================================
# 6. Evaluation metrics
# ============================================================
@torch.no_grad()
def compute_ece(confidences, correct, n_bins=10):
    confidences = torch.cat(confidences)
    correct = torch.cat(correct).float()

    ece = torch.zeros([], device=confidences.device)

    for i in range(n_bins):
        lo = i / n_bins
        hi = (i + 1) / n_bins

        mask = (confidences > lo) & (confidences <= hi)
        if mask.any():
            bin_conf = confidences[mask].mean()
            bin_acc = correct[mask].mean()
            ece += mask.float().mean() * (bin_conf - bin_acc).abs()

    return ece.item()

#hard_ce, ppl, top1 acc, top5 acc, top1 emb distance, expected emb distance, average iv, ece
@torch.no_grad()
def evaluate(model, loader, ext_emb, max_batches=None, iv_chunk_size=128):
    """
    Evaluate a model on a loader.

    max_batches=None means evaluate the full split. During training curves we use
    a smaller max_batches value to keep checkpoint evaluation affordable; final
    validation/test evaluation uses the full split by default.
    """
    model.eval()

    total_nll = 0.0
    total_tokens = 0

    total_correct = 0
    total_top5 = 0

    top1_emb_dist_sum = 0.0
    expected_emb_dist_sum = 0.0
    average_iv_sum = 0.0

    confidences = []
    correctness = []

    for step, batch in enumerate(loader):
        if max_batches is not None and step >= max_batches:
            break

        input_ids = batch["input_ids"].to(device)
        outputs = model(input_ids=input_ids)
        logits = outputs.logits

        shift_logits = logits[:, :-1, :].contiguous()
        shift_labels = input_ids[:, 1:].contiguous()

        vocab_size = shift_logits.size(-1)
        logits_flat = shift_logits.view(-1, vocab_size)
        labels_flat = shift_labels.view(-1)

        # standard hard-target CE
        ce_sum = F.cross_entropy(logits_flat, labels_flat, reduction="sum")
        total_nll += ce_sum.item()
        total_tokens += labels_flat.numel()

        # top-1 accuracy+top-5 accuracy
        probs = F.softmax(logits_flat, dim=-1)
        conf, pred = probs.max(dim=-1)

        correct = pred.eq(labels_flat)
        total_correct += correct.sum().item()

        top5 = logits_flat.topk(5, dim=-1).indices
        total_top5 += top5.eq(labels_flat.unsqueeze(-1)).any(dim=-1).sum().item()

        confidences.append(conf.detach())
        correctness.append(correct.detach())

        # top-1 embedding distance
        target_emb = ext_emb[labels_flat]
        pred_emb = ext_emb[pred]

        # disntance between top-1 predicted token and target token
        top1_dist = 1.0 - (pred_emb * target_emb).sum(dim=-1)
        top1_emb_dist_sum += top1_dist.sum().item()

        # expected embedding distance
        expected_emb = probs @ ext_emb
        expected_emb = F.normalize(expected_emb, p=2, dim=-1)
        expected_dist = 1.0 - (expected_emb * target_emb).sum(dim=-1)
        expected_emb_dist_sum += expected_dist.sum().item()

        for start in range(0, logits_flat.size(0), iv_chunk_size):
            end = min(start + iv_chunk_size, logits_flat.size(0))

            probs_chunk = probs[start:end]
            target_emb_chunk = target_emb[start:end]

            #IV-like metric/expected embedding distance
            sims = target_emb_chunk @ ext_emb.T
            distances = 1.0 - sims

            average_iv = (probs_chunk * distances).sum(dim=-1)
            average_iv_sum += average_iv.sum().item()

    avg_ce = total_nll / total_tokens
    ppl = math.exp(min(avg_ce, 20))

    metrics = {
        "hard_ce": avg_ce,
        "perplexity": ppl,
        "accuracy": total_correct / total_tokens,
        "top5_accuracy": total_top5 / total_tokens,
        "top1_embedding_distance": top1_emb_dist_sum / total_tokens,
        "expected_embedding_distance": expected_emb_dist_sum / total_tokens,
        "average_iv": average_iv_sum / total_tokens,
        "ece": compute_ece(confidences, correctness),
    }

    model.train()
    return metrics

# ============================================================
# 7. Experiment runner
# ============================================================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import gc
import time

sns.set_theme(style="whitegrid")

# One full pass over the grouped WikiText-2 train split.
FULL_EPOCH_STEPS = len(train_loader)
FULL_MAX_TRAIN_STEPS = FULL_EPOCH_STEPS
FULL_EVAL_EVERY = 500
CURVE_EVAL_MAX_BATCHES = 50
FINAL_EVAL_MAX_BATCHES = None  # None = full validation/test split for final metrics.

print("Full WikiText-2 train steps:", FULL_EPOCH_STEPS)
print("Approx target tokens per epoch:", FULL_EPOCH_STEPS * cfg.batch_size * (cfg.block_size - 1))


def make_model():
    model_config = GPT2Config(
        vocab_size=len(tokenizer),
        n_positions=cfg.block_size,
        n_ctx=cfg.block_size,
        n_embd=cfg.n_embd,
        n_layer=cfg.n_layer,
        n_head=cfg.n_head,
        bos_token_id=tokenizer.bos_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )
    return GPT2LMHeadModel(model_config).to(device)


def reset_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def run_experiment(
    run_name,
    objective,
    tau=None,
    label_smoothing_epsilon=0.05,
    max_train_steps=FULL_MAX_TRAIN_STEPS,
    eval_every=FULL_EVAL_EVERY,
    run_seed=42,
    eval_max_batches=CURVE_EVAL_MAX_BATCHES,
    final_eval_max_batches=FINAL_EVAL_MAX_BATCHES,
):
    print(f"\n===== Running {run_name} =====")

    reset_seed(run_seed)

    model = make_model()
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=cfg.lr,
        weight_decay=cfg.weight_decay,
    )

    history = []
    global_step = 0
    model.train()

    start_time = time.perf_counter()
    tokens_seen = 0

    progress = tqdm(total=max_train_steps, desc=run_name)

    while global_step < max_train_steps:
        for batch in train_loader:
            input_ids = batch["input_ids"].to(device)

            outputs = model(input_ids=input_ids)
            logits = outputs.logits

            if objective == "hard":
                loss = hard_next_token_loss(logits, input_ids)
            elif objective == "label_smoothing":
                loss = label_smoothing_next_token_loss(
                    logits,
                    input_ids,
                    epsilon=label_smoothing_epsilon,
                )
            elif objective == "soft":
                loss = soft_target_next_token_loss(
                    logits,
                    input_ids,
                    ext_emb=ext_emb,
                    tau=tau,
                    chunk_size=cfg.soft_loss_chunk_size,
                )
            else:
                raise ValueError("objective must be 'hard', 'label_smoothing', or 'soft'")

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            global_step += 1
            tokens_seen += input_ids[:, 1:].numel()
            elapsed_sec = time.perf_counter() - start_time

            progress.update(1)
            progress.set_postfix({"loss": round(loss.item(), 4)})

            if global_step % eval_every == 0 or global_step == max_train_steps:
                metrics = evaluate(
                    model,
                    valid_loader,
                    ext_emb,
                    max_batches=eval_max_batches,
                )
                row = {
                    "run": run_name,
                    "objective": objective,
                    "tau": tau if tau is not None else "none",
                    "label_smoothing_epsilon": (
                        label_smoothing_epsilon if objective == "label_smoothing" else "none"
                    ),
                    "step": global_step,
                    "tokens_seen": tokens_seen,
                    "elapsed_sec": elapsed_sec,
                    **metrics,
                }
                history.append(row)

                print(f"\nEval {run_name} step {global_step}")
                print(f"perplexity: {metrics['perplexity']:.4f}")
                print(f"accuracy: {metrics['accuracy']:.4f}")
                print(f"top5_accuracy: {metrics['top5_accuracy']:.4f}")
                print(f"expected_embedding_distance: {metrics['expected_embedding_distance']:.4f}")
                print(f"ece: {metrics['ece']:.4f}")

            if global_step >= max_train_steps:
                break

    progress.close()

    final_valid_metrics = evaluate(
        model,
        valid_loader,
        ext_emb,
        max_batches=final_eval_max_batches,
    )
    final_test_metrics = evaluate(
        model,
        test_loader,
        ext_emb,
        max_batches=final_eval_max_batches,
    )

    final = {
        "run": run_name,
        "objective": objective,
        "tau": tau if tau is not None else "none",
        "label_smoothing_epsilon": (
            label_smoothing_epsilon if objective == "label_smoothing" else "none"
        ),
        "step": global_step,
        "tokens_seen": tokens_seen,
        "elapsed_sec": time.perf_counter() - start_time,
        **final_valid_metrics,
    }
    for k, v in final_test_metrics.items():
        final[f"test_{k}"] = v

    del model
    torch.cuda.empty_cache()
    gc.collect()

    return history, final

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

@torch.no_grad()
def inspect_soft_targets(ext_emb, labels, taus=[0.03, 0.05, 0.07, 0.10, 0.20]):
    rows = []
    labels = labels.to(ext_emb.device)

    for tau in taus:
        target_emb = ext_emb[labels]
        sims = target_emb @ ext_emb.T
        q = F.softmax(sims / tau, dim=-1)

        entropy = -(q * torch.log(q + 1e-12)).sum(dim=-1)
        top1_mass = q.max(dim=-1).values
        top10_mass = q.topk(10, dim=-1).values.sum(dim=-1)
        top100_mass = q.topk(100, dim=-1).values.sum(dim=-1)

        rows.append({
            "tau": tau,
            "entropy": entropy.mean().item(),
            "top1_mass": top1_mass.mean().item(),
            "top10_mass": top10_mass.mean().item(),
            "top100_mass": top100_mass.mean().item(),
        })

    return pd.DataFrame(rows)

batch = next(iter(train_loader))
sample_labels = batch["input_ids"][:, 1:].reshape(-1)[:256].to(device)

soft_stats = inspect_soft_targets(
    ext_emb,
    sample_labels,
    taus=[0.03, 0.05, 0.07, 0.10, 0.20],
)

display(soft_stats)

sns.lineplot(data=soft_stats, x="tau", y="top1_mass", marker="o", label="top1")
sns.lineplot(data=soft_stats, x="tau", y="top10_mass", marker="o", label="top10")
sns.lineplot(data=soft_stats, x="tau", y="top100_mass", marker="o", label="top100")
plt.title("Soft Target Probability Mass by Tau")
plt.ylabel("Probability mass")
plt.show()

# ============================================================
# 8. Run full WikiText-2 one-epoch sweep
# ============================================================
experiments = [
    {"run_name": "hard_baseline", "objective": "hard", "tau": None},
    {"run_name": "label_smoothing_0.05", "objective": "label_smoothing", "tau": None, "epsilon": 0.05},
    {"run_name": "soft_tau_0.05", "objective": "soft", "tau": 0.05},
    {"run_name": "soft_tau_0.06", "objective": "soft", "tau": 0.06},
]

# For a quick smoke test, use seeds = [42].
# For the final project run, use all three seeds.
seeds = [42, 43, 44]

all_history = []
final_results = []

for s in seeds:
    for exp in experiments:
        run_name = f'{exp["run_name"]}_seed{s}'

        hist, final = run_experiment(
            run_name=run_name,
            objective=exp["objective"],
            tau=exp["tau"],
            label_smoothing_epsilon=exp.get("epsilon", cfg.label_smoothing_epsilon),
            max_train_steps=FULL_MAX_TRAIN_STEPS,
            eval_every=FULL_EVAL_EVERY,
            run_seed=s,
            eval_max_batches=CURVE_EVAL_MAX_BATCHES,
            final_eval_max_batches=FINAL_EVAL_MAX_BATCHES,
        )

        for row in hist:
            row["seed"] = s
            row["base_run"] = exp["run_name"]

        final["seed"] = s
        final["base_run"] = exp["run_name"]

        all_history.extend(hist)
        final_results.append(final)

history_df = pd.DataFrame(all_history)
final_df = pd.DataFrame(final_results)

display(final_df)

"""## Results and analysis

The results are organised around two axes.

1. **Efficiency axis**: Does a training objective improve performance as a function of training data (`tokens_seen`) or as a function of computational time (`wall-clock time`)?
2. **Evaluation-value axis**: Does the conclusion change when the evaluation value is exact-token prediction (`perplexity`) versus representational closeness (`expected_embedding_distance`)?

The main figure is a 2 x 2 trade-off matrix. Columns compare data efficiency and runtime efficiency; rows compare PPL evaluation and expected-embedding-distance evaluation. Label smoothing is included as a non-representational soft-target baseline, so improvements from the similarity-based soft target cannot be attributed only to softening the labels.

"""

# ============================================================
# 9. Paper-style plotting setup
# ============================================================
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

sns.set_theme(style="whitegrid", context="paper", font_scale=1.25)

METHOD_ORDER = ["hard_baseline", "label_smoothing_0.05", "soft_tau_0.05", "soft_tau_0.06"]
METHOD_LABELS = {
    "hard_baseline": "Hard target",
    "label_smoothing_0.05": "Label smoothing",
    "soft_tau_0.05": "Soft target, tau=0.05",
    "soft_tau_0.06": "Soft target, tau=0.06",
}
METHOD_PALETTE = {
    "Hard target": "#4C72B0",
    "Label smoothing": "#8172B3",
    "Soft target, tau=0.05": "#DD8452",
    "Soft target, tau=0.06": "#55A868",
}

history_plot = history_df.copy()
final_plot = final_df.copy()

history_plot["method"] = pd.Categorical(
    history_plot["base_run"].map(METHOD_LABELS),
    categories=[METHOD_LABELS[m] for m in METHOD_ORDER],
    ordered=True,
)
final_plot["method"] = pd.Categorical(
    final_plot["base_run"].map(METHOD_LABELS),
    categories=[METHOD_LABELS[m] for m in METHOD_ORDER],
    ordered=True,
)

history_plot["tokens_seen_m"] = history_plot["tokens_seen"] / 1_000_000
history_plot["elapsed_sec_plot"] = history_plot["elapsed_sec"]
final_plot["elapsed_sec_plot"] = final_plot["elapsed_sec"]

# Check that the key result columns exist before plotting.
required_cols = ["perplexity", "expected_embedding_distance", "tokens_seen", "elapsed_sec", "seed", "base_run"]
missing = [c for c in required_cols if c not in history_plot.columns]
if missing:
    raise ValueError(f"Missing columns in history_df: {missing}")

# ============================================================
# Figure 1. Efficiency trade-off matrix
# ============================================================
# Columns show the efficiency axis. Rows show the evaluation value.

eval_history = history_plot.dropna(
    subset=["perplexity", "expected_embedding_distance"]
).copy()

fig, axes = plt.subplots(2, 2, figsize=(12, 8), sharex="col")

panels = [
    (axes[0, 0], "tokens_seen_m", "perplexity"),
    (axes[0, 1], "elapsed_sec_plot", "perplexity"),
    (axes[1, 0], "tokens_seen_m", "expected_embedding_distance"),
    (axes[1, 1], "elapsed_sec_plot", "expected_embedding_distance"),
]

for ax, x, y in panels:
    sns.lineplot(
        data=eval_history,
        x=x,
        y=y,
        hue="method",
        hue_order=[METHOD_LABELS[m] for m in METHOD_ORDER],
        palette=METHOD_PALETTE,
        marker="o",
        errorbar="sd",
        linewidth=2,
        ax=ax,
    )

axes[0, 0].set_title("Training-data axis")
axes[0, 1].set_title("Runtime axis")
axes[0, 0].set_ylabel("Validation PPL\n(lower is better)")
axes[1, 0].set_ylabel("Expected embedding distance\n(lower is better)")
axes[0, 1].set_ylabel("")
axes[1, 1].set_ylabel("")
axes[1, 0].set_xlabel("Training tokens seen (millions)")
axes[1, 1].set_xlabel("Wall-clock time (seconds)")
axes[0, 0].set_xlabel("")
axes[0, 1].set_xlabel("")

handles, labels = axes[0, 0].get_legend_handles_labels()
for ax in axes.flat:
    leg = ax.get_legend()
    if leg is not None:
        leg.remove()

fig.legend(
    handles,
    labels,
    loc="lower center",
    ncol=4,
    frameon=False,
    bbox_to_anchor=(0.5, -0.03),
)
sns.despine(fig=fig)
plt.tight_layout()

from pathlib import Path
FIG_DIR = Path("figures")
FIG_DIR.mkdir(exist_ok=True)
fig.savefig(FIG_DIR / "efficiency_tradeoff_matrix.pdf", bbox_inches="tight")
fig.savefig(FIG_DIR / "efficiency_tradeoff_matrix.png", dpi=300, bbox_inches="tight")

plt.show()

# detailed?
# ============================================================
# Figure 1. Relative efficiency trade-off matrix
# Difference from hard-target baseline
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

sns.set_theme(style="whitegrid", context="paper", font_scale=1.25)

# ------------------------------------------------------------
# 1. Prepare validation history
# ------------------------------------------------------------
eval_history = history_plot.dropna(
    subset=["perplexity", "expected_embedding_distance"]
).copy()

# Make x-axis columns if needed
if "tokens_seen_m" not in eval_history.columns:
    eval_history["tokens_seen_m"] = eval_history["tokens_seen"] / 1_000_000

if "elapsed_sec_plot" not in eval_history.columns:
    eval_history["elapsed_sec_plot"] = eval_history["elapsed_sec"]

method_order = [METHOD_LABELS[m] for m in METHOD_ORDER]

eval_history["method"] = pd.Categorical(
    eval_history["method"],
    categories=method_order,
    ordered=True,
)

# Aggregate over seeds at each method-step
agg = (
    eval_history
    .groupby(["method", "step"], observed=True)
    .agg(
        tokens_seen_m=("tokens_seen_m", "mean"),
        elapsed_sec=("elapsed_sec_plot", "mean"),
        ppl=("perplexity", "mean"),
        ppl_std=("perplexity", "std"),
        eed=("expected_embedding_distance", "mean"),
        eed_std=("expected_embedding_distance", "std"),
    )
    .reset_index()
)

agg[["ppl_std", "eed_std"]] = agg[["ppl_std", "eed_std"]].fillna(0.0)

hard_name = "Hard target"

hard_by_step = (
    agg[agg["method"] == hard_name]
    [["step", "ppl", "eed"]]
    .rename(columns={"ppl": "hard_ppl", "eed": "hard_eed"})
)

# ------------------------------------------------------------
# 2. Training-data axis: compare methods at same step/tokens
# ------------------------------------------------------------
delta_tokens = agg.merge(hard_by_step, on="step", how="left")

delta_tokens["delta_ppl"] = delta_tokens["ppl"] - delta_tokens["hard_ppl"]
delta_tokens["delta_eed"] = delta_tokens["eed"] - delta_tokens["hard_eed"]
delta_tokens["axis_type"] = "tokens"

# Remove hard target from relative curves; it is always zero
delta_tokens = delta_tokens[delta_tokens["method"] != hard_name].copy()


# ------------------------------------------------------------
# 3. Runtime axis: compare methods to hard target at same time
#    using interpolation of the hard-target curve
# ------------------------------------------------------------
hard_curve = agg[agg["method"] == hard_name].sort_values("elapsed_sec")

hard_time = hard_curve["elapsed_sec"].to_numpy()
hard_ppl = hard_curve["ppl"].to_numpy()
hard_eed = hard_curve["eed"].to_numpy()

runtime_rows = []

for method in method_order:
    if method == hard_name:
        continue

    d = agg[agg["method"] == method].sort_values("elapsed_sec").copy()

    # Only compare within the hard-target time range
    d = d[
        (d["elapsed_sec"] >= hard_time.min()) &
        (d["elapsed_sec"] <= hard_time.max())
    ].copy()

    if len(d) == 0:
        continue

    interp_hard_ppl = np.interp(d["elapsed_sec"], hard_time, hard_ppl)
    interp_hard_eed = np.interp(d["elapsed_sec"], hard_time, hard_eed)

    d["hard_ppl_runtime"] = interp_hard_ppl
    d["hard_eed_runtime"] = interp_hard_eed

    d["delta_ppl"] = d["ppl"] - d["hard_ppl_runtime"]
    d["delta_eed"] = d["eed"] - d["hard_eed_runtime"]
    d["axis_type"] = "runtime"

    runtime_rows.append(d)

delta_runtime = pd.concat(runtime_rows, ignore_index=True)


# ------------------------------------------------------------
# 4. Plot settings
# ------------------------------------------------------------
colors = {
    "Label smoothing": "#8172B2",
    "Soft target, tau=0.05": "#DD8452",
    "Soft target, tau=0.06": "#55A868",
}

linestyles = {
    "Label smoothing": "--",
    "Soft target, tau=0.05": "-",
    "Soft target, tau=0.06": "-.",
}

markers = {
    "Label smoothing": "s",
    "Soft target, tau=0.05": "D",
    "Soft target, tau=0.06": "^",
}

plot_methods = [
    "Label smoothing",
    "Soft target, tau=0.05",
    "Soft target, tau=0.06",
]


def draw_relative_panel(ax, data, x_col, y_col, xlabel=None, ylabel=None, title=None):
    for method in plot_methods:
        d = data[data["method"] == method].sort_values(x_col)
        if len(d) == 0:
            continue

        ax.plot(
            d[x_col],
            d[y_col],
            label=method,
            color=colors[method],
            linestyle=linestyles[method],
            marker=markers[method],
            linewidth=2.4,
            markersize=6,
            markeredgecolor="white",
            markeredgewidth=0.8,
        )

    # hard-target reference line
    ax.axhline(
        0,
        color="black",
        linewidth=1.2,
        linestyle=":",
        alpha=0.8,
    )

    if title:
        ax.set_title(title, fontsize=15, pad=8)
    if xlabel:
        ax.set_xlabel(xlabel, fontsize=13)
    if ylabel:
        ax.set_ylabel(ylabel, fontsize=13)

    ax.grid(True, alpha=0.30)
    ax.tick_params(labelsize=11)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


# ------------------------------------------------------------
# 5. Draw figure
# ------------------------------------------------------------
fig, axes = plt.subplots(2, 2, figsize=(12.5, 8.2), sharex="col")

draw_relative_panel(
    axes[0, 0],
    delta_tokens,
    x_col="tokens_seen_m",
    y_col="delta_ppl",
    title="By training tokens seen",
    ylabel="Δ validation PPL vs hard target\n(lower is better)",
)

draw_relative_panel(
    axes[0, 1],
    delta_runtime,
    x_col="elapsed_sec",
    y_col="delta_ppl",
    title="By wall-clock time",
)

draw_relative_panel(
    axes[1, 0],
    delta_tokens,
    x_col="tokens_seen_m",
    y_col="delta_eed",
    xlabel="Training tokens seen (millions)",
    ylabel="Δ expected embedding distance\nvs hard target\n(lower is better)",
)

draw_relative_panel(
    axes[1, 1],
    delta_runtime,
    x_col="elapsed_sec",
    y_col="delta_eed",
    xlabel="Wall-clock time (seconds)",
)

# Set symmetric-ish y-limits around zero for easier reading
for ax in axes[0, :]:
    ymin, ymax = ax.get_ylim()
    pad = max(abs(ymin), abs(ymax)) * 1.10
    ax.set_ylim(-pad, pad)

for ax in axes[1, :]:
    ymin, ymax = ax.get_ylim()
    pad = max(abs(ymin), abs(ymax)) * 1.10
    ax.set_ylim(-pad, pad)

# Global legend
handles, labels = axes[0, 0].get_legend_handles_labels()
fig.legend(
    handles,
    labels,
    loc="lower center",
    ncol=3,
    frameon=False,
    bbox_to_anchor=(0.5, -0.01),
    fontsize=11,
)

fig.suptitle(
    "Efficiency trade-off relative to hard-target training",
    fontsize=16,
    y=1.01,
)

plt.tight_layout(rect=[0, 0.05, 1, 0.98])

FIG_DIR = Path("figures")
FIG_DIR.mkdir(exist_ok=True)

fig.savefig(FIG_DIR / "efficiency_tradeoff_relative.pdf", bbox_inches="tight")
fig.savefig(FIG_DIR / "efficiency_tradeoff_relative.png", dpi=300, bbox_inches="tight")

plt.show()

# ============================================================
# Supplementary figure. Final relative changes against hard target
# ============================================================
# Positive values mean improvement over the hard-target baseline on the held-out test split.
metrics = {
    "test_perplexity": "PPL",
    "test_expected_embedding_distance": "Expected emb. distance",
    "test_accuracy": "Accuracy",
    "test_top5_accuracy": "Top-5 accuracy",
    "test_top1_embedding_distance": "Top-1 emb. distance",
    "test_ece": "ECE",
}
lower_is_better = {
    "test_perplexity": True,
    "test_expected_embedding_distance": True,
    "test_accuracy": False,
    "test_top5_accuracy": False,
    "test_top1_embedding_distance": True,
    "test_ece": True,
}

rows = []
for seed, group in final_df.groupby("seed"):
    baseline = group[group["base_run"] == "hard_baseline"].iloc[0]
    for _, row in group[group["base_run"] != "hard_baseline"].iterrows():
        for metric, label in metrics.items():
            base_value = baseline[metric]
            model_value = row[metric]
            if lower_is_better[metric]:
                improvement = 100 * (base_value - model_value) / base_value
            else:
                improvement = 100 * (model_value - base_value) / base_value
            rows.append({
                "seed": seed,
                "base_run": row["base_run"],
                "method": METHOD_LABELS[row["base_run"]],
                "metric": label,
                "relative_improvement_pct": improvement,
            })

relative_df = pd.DataFrame(rows)
metric_order = ["PPL", "Expected emb. distance", "Accuracy", "Top-5 accuracy", "Top-1 emb. distance", "ECE"]

plt.figure(figsize=(10, 5.5))
sns.barplot(
    data=relative_df,
    x="relative_improvement_pct",
    y="metric",
    hue="method",
    order=metric_order,
    palette=METHOD_PALETTE,
    errorbar="sd",
)
plt.axvline(0, color="black", linewidth=1)
plt.xlabel("Relative improvement over hard-target baseline (%)")
plt.ylabel("")
plt.title("Supplementary: final relative change vs hard target")
plt.legend(title="", frameon=False, loc="lower right")
sns.despine()
plt.tight_layout()
plt.show()

# ============================================================
# Table 1. Final held-out test summary
# ============================================================
test_summary_metrics = [
    "test_perplexity",
    "test_expected_embedding_distance",
    "test_accuracy",
    "test_top5_accuracy",
    "test_ece",
]

summary_df = final_df.groupby("base_run")[test_summary_metrics].agg(["mean", "std"])
summary_df = summary_df.rename(index=METHOD_LABELS)
display(summary_df)

# ============================================================
# Table 2. Runtime overhead at the final checkpoint
# ============================================================
runtime_summary = final_df.groupby("base_run").agg({
    "tokens_seen": ["mean", "std"],
    "elapsed_sec": ["mean", "std"],
    "test_perplexity": ["mean", "std"],
    "test_expected_embedding_distance": ["mean", "std"],
    "test_accuracy": ["mean", "std"],
})
runtime_summary = runtime_summary.rename(index=METHOD_LABELS)
display(runtime_summary)

runtime_plot = final_plot.copy()
plt.figure(figsize=(7, 4))
sns.barplot(
    data=runtime_plot,
    x="method",
    y="elapsed_sec",
    hue="method",
    order=[METHOD_LABELS[m] for m in METHOD_ORDER],
    palette=METHOD_PALETTE,
    errorbar="sd",
    legend=False,
)
plt.ylabel("Runtime for 1000 steps (seconds)")
plt.xlabel("")
plt.title("Per-step runtime overhead")
plt.xticks(rotation=20, ha="right")
sns.despine()
plt.tight_layout()
plt.show()

# ============================================================
# Threshold-based required data/runtime summary
# ============================================================
def threshold_summary(eval_history, metric, threshold, lower_is_better=True):
    rows = []

    for base_run, group in eval_history.groupby("base_run"):
        for seed, seed_group in group.groupby("seed"):
            seed_group = seed_group.sort_values("step")

            if lower_is_better:
                hit = seed_group[seed_group[metric] <= threshold]
            else:
                hit = seed_group[seed_group[metric] >= threshold]

            if len(hit) == 0:
                rows.append({
                    "base_run": base_run,
                    "method": METHOD_LABELS[base_run],
                    "seed": seed,
                    "metric": metric,
                    "threshold": threshold,
                    "tokens_required": np.nan,
                    "seconds_required": np.nan,
                    "hit": False,
                })
            else:
                first = hit.iloc[0]
                rows.append({
                    "base_run": base_run,
                    "method": METHOD_LABELS[base_run],
                    "seed": seed,
                    "metric": metric,
                    "threshold": threshold,
                    "tokens_required": first["tokens_seen"],
                    "seconds_required": first["elapsed_sec"],
                    "hit": True,
                })

    return pd.DataFrame(rows)

threshold_history = history_plot.dropna(subset=["perplexity", "expected_embedding_distance"]).copy()

required_df = pd.concat([
    threshold_summary(threshold_history, metric="perplexity", threshold=600, lower_is_better=True),
    threshold_summary(threshold_history, metric="expected_embedding_distance", threshold=0.42, lower_is_better=True),
], ignore_index=True)

required_summary = required_df.groupby(["metric", "method"]).agg({
    "hit": "mean",
    "tokens_required": ["mean", "std"],
    "seconds_required": ["mean", "std"],
})

display(required_df)
display(required_summary)
